FROM debian:stretch-slim

ENV ASTERISK_VERSION 18.3.0

RUN apt update && \
    apt install -y tcpdump nano iputils-ping git curl wget libnewt-dev uuid-runtime libedit-dev mpg123 ffmpeg libssl-dev libncurses5-dev subversion libsqlite3-dev build-essential libjansson-dev libxml2-dev uuid-dev apt-utils \
    && wget https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-${ASTERISK_VERSION}.tar.gz \
    && tar xzf asterisk-${ASTERISK_VERSION}.tar.gz \
    && cd asterisk-${ASTERISK_VERSION} \
    && useradd --system asterisk \
    && sh contrib/scripts/get_mp3_source.sh \
#install_prereq supposed to do nothing as of now, kept at test, gets stuck at picking ITU, maybe because we gotta put +971?
    && ./contrib/scripts/install_prereq test \
    && ./configure --with-jansson-bundled \
    && make menuselect.makeopts \
    && ./menuselect/menuselect \
       --disable BUILD_NATIVE \ 
#to avoid platform issues
       --enable BETTER_BACKTRACES \
       --enable chan_mobile \
       --enable chan_ooh323 \
       --enable format_mp3 \
       --enable res_config_mysql \
       --disable app_mysql \
       --disable cdr_mysql \
       
       --enable-category MENUSELECT_APPS \
       --disable app_skel \
       --disable app_fax \

       --enable-category MENUSELECT_BRIDGES \
       
       --enable-category MENUSELECT_CDR \
       --disable cdr_syslog \
       
       --enable-category MENUSELECT_CEL \
       --enable-category MENUSELECT_CHANNELS \
       --enable-category MENUSELECT_CODECS \
       --enable-category MENUSELECT_FORMATS \
       --enable-category MENUSELECT_FUNCS \
       --enable-category MENUSELECT_PBX \
       
       --enable-category MENUSELECT_RES \
       --disable res_mwi_external \
       --disable res_pktccops \
       --disable res_endpoint_stats \
       --disable res_chan_stats \
        
       --enable-category MENUSELECT_TESTS \
        
       --disable-category MENUSELECT_UTILS \
       --enable astcanary \
       --enable astdb2sqlite3 \
       --enable astdb2bdb \
 
       --disable-category MENUSELECT_AGIS \
       
       #in a dilemma whether to remove below CORE_SOUNDS as docker doesnt need sounds itself, can be load from /var/lib/asterisk/sounds
       #CORE_SOUNDS MOH, EXTRA SOUNDS
       --disable-category MENUSELECT_CORE_SOUNDS \
       #--enable CORE-SOUNDS-EN-WAV \
       #--enable CORE-SOUNDS-EN-ULAW \
       #--enable CORE-SOUNDS-EN-ALAW \
       #--enable CORE-SOUNDS-EN-GSM \
       #--enable CORE-SOUNDS-EN-G729 \
       #--enable CORE-SOUNDS-EN-G722 \
       #--enable CORE-SOUNDS-EN-SLN16 \
       #--enable CORE-SOUNDS-EN-SIREN7 \
       #--enable CORE-SOUNDS-EN-SIREN14 \

       --disable-category MENUSELECT_MOH \
       #--enable MOH-OPSOUND-WAV \       
       #--enable MOH-OPSOUND-ULAW \
       #--enable MOH-OPSOUND-ALAW \
       #--enable MOH-OPSOUND-GSM \
       
       --disable-category MENUSELECT_EXTRA_SOUNDS \
       #--enable EXTRA-SOUNDS-EN-WAV \
       #--enable EXTRA-SOUNDS-EN-ULAW \
       #--enable EXTRA-SOUNDS-EN-ALAW \
       #--enable EXTRA-SOUNDS-EN-GSM \
       menuselect.makeopts \
#nproc gives the no of CPU cores/threads available, -j for jobs depending on laptop the speed, for super fast builds suggested tmpfs
    && make -j $(nproc) \
    && make install \
    && make samples \
    && make config \
    && ldconfig \

   # && devpackages=`dpkg -l|grep '\-dev'|awk '{print $2}'|xargs` \
   #debconf, debianfrontend only runs for the next one apt command
   #noninteractive is anti frontend, completely silent and unobstructive, for auto installs, uses default answers, to change that preseed debconf db?
    && DEBIAN_FRONTEND=noninteractive apt-get --yes purge --auto-remove \
    autoconf build-essential git subversion bzip2 cpp m4 make patch perl perl-modules pkg-config xz-utils ${devpackages} \

    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /etc/asterisk/ /var/spool/asterisk/fax \
    && chown -R asterisk:asterisk /etc/asterisk \
    && chown -R asterisk:asterisk /var/spool/asterisk \
    && chown -R asterisk:asterisk /var/log/asterisk \
    && chown -R asterisk:asterisk /usr/lib/asterisk \
    && chmod -R 750 /var/spool/asterisk \
    && cd .. \
    && rm asterisk-${ASTERISK_VERSION}.tar.gz \
    && rm -R asterisk-${ASTERISK_VERSION} \
    && dpkg -l
    && mkdir /etc/asterisk/keys

EXPOSE 5060/udp 5060/tcp 4569/udp 5061 8088 8089

VOLUME /etc/asterisk /var/lib/asterisk /var/spool/asterisk /var/log/asterisk

#run foreground in high verbosity every time a container is run
ENTRYPOINT ["/usr/sbin/asterisk", "-fvvv"]
