version: '3.9'
services:
  asterisk:
    container_name: asterisk
    image: team6/dockerserver_1
    ports:
     - "192.168.1.29:5060:5060/udp"
     - "192.168.1.29:5060:5060/tcp"
     - "192.168.1.29:5061:5061" 
     - "192.168.1.29:10000-10099:10000-10099/udp"
     - "192.168.1.29:8088:8088" #built in asterisk http server
     - "192.168.1.29:8089:8089" #ssl,wss,webrtc
     - "192.168.1.29:5038:5038"
    volumes:
     - Asterisk-etc:/etc/asterisk
     - Asterisk-lib:/var/lib/asterisk
     - Asterisk-spool:/var/spool/asterisk
     #optional volume log
     - Asterisk-log:/var/log/asterisk
    networks:
      default:
        ipv4_address: 10.1.2.10
    tty: true
  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrestest
    volumes:
      - "${PWD}/.pgdata:/var/lib/postgresql/data"
      - "${PWD}/.pgsocket:/var/run/postgresql"
      - "${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"
    networks:
      default:
        ipv4_address: 10.1.2.11
    tty: true
    restart: always
networks:
  default:
    ipam:
      config:
       - subnet: 10.1.2.0/24

volumes:
  Asterisk-etc:
    external: true
  Asterisk-lib:
    external: true
  Asterisk-spool:
    external: true
  Asterisk-log:
    external: true
